### ISSUE TITLE
Wrong inlay hints of unsafe.Sizeof(AType{})

### ISSUE THREAD

**Issue by HwHgoo** [golang/vscode-go#3146]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <go version go1.19.1 linux/amd64>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <golang.org/x/tools/gopls v0.14.2>
* Check your installed extensions to get the version of the VS Code Go extension
	- <v0.40.1>
</details>

### Describe the bug
Inlay hint shows wrong value of unsafe.Sizeof(AType{}). And it only occurs when AType has an auto padding at the end.

### Steps to reproduce the behavior:
See the screenshot.

### Screenshots or recordings
![image](https://github.com/golang/vscode-go/assets/36889966/839e7e5a-a71a-488b-932e-0b94e3c285d2)

**Comment by HwHgoo** [comment]
I believe it should blame to gopls:
![image](https://github.com/golang/vscode-go/assets/36889966/22683d9b-4bef-40bb-b156-8f928e39f473)

**Comment by hyangah** [comment]
@HwHgoo thanks for the report. Can you please try the gopls with `go1.22rc1`?
I think this is fixed in go1.22. (https://github.com/golang/go/issues/61035)

**Comment by HwHgoo** [comment]
> @HwHgoo thanks for the report. Can you please try the gopls with `go1.22rc1`? I think this is fixed in go1.22. ([golang/go#61035](https://github.com/golang/go/issues/61035))

![version](https://github.com/golang/vscode-go/assets/36889966/9bae9000-025d-45c8-9dad-cfbf6e2fb7f2)
![image](https://github.com/golang/vscode-go/assets/36889966/fdd37245-d8e7-4b0a-8b3f-1def7e597e9b)

It seems go1.22rc1 doesn't fix it as expected. I don't know if I'm doing right: I build the go1.22rc and override the path of go which originally is `/usr/bin/go`  by simply doing `export PATH=$PATH_TO_GO1.22rc1:$PATH`.

**Comment by hyangah** [comment]
@HwHgoo Can you check what version of go was used to build the gopls? 

```
gopls -v version
```
Or, use the Go explorer UI to inspect the tools versions.
<img width="531" alt="Screenshot 2024-01-23 at 10 25 07 AM" src="https://github.com/golang/vscode-go/assets/4999471/6d6bdca2-313c-4ab5-85fd-1d855daa16bb">

If it's not built with go1.22rc1, run "Go: Install/Update Tools".

**Comment by HwHgoo** [comment]
Yes it's fixed. 
![image](https://github.com/golang/vscode-go/assets/36889966/83215c18-f48e-4a33-94b7-add2d3d91dca)
But it's confusing that even I do `export PATH=$PATH_TO_GO122rc1:$PATH`, `/usr/bin/go` is used when I run `go install golang.org/x/tools/gopls@latest`.
Thank you for replies.
